project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: https://api.crowdin.com

preserve_hierarchy: true

files:
  - source: /web/src/locales/en/translation.json
    translation: /web/src/locales/%two_letters_code%/translation.json
    languages_mapping:
      two_letters_code:
        bg: bg
        fr: fr
        ro: ro
        ru: ru
        ua: ua
        zh: zh
