apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "torrserver.fullname" . }}
  labels:
    {{- include "torrserver.labels" . | nindent 4 }}
data:
  # Additional runtime configuration can be projected here
  # and mounted as files inside the container if needed.
  APP_PORT: {{ .Values.config.port | quote }}
  APP_CONF_PATH: {{ .Values.config.confPath | quote }}
  APP_TORR_DIR: {{ .Values.config.torrDir | quote }}
